# Generated by Django 3.1 on 2020-08-29 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField(default=10000000, unique=True)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')])),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$')])),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{2}[:][0-9]{2}$', 'in HH:MM')])),
                ('status', models.CharField(default='T', max_length=1, validators=[django.core.validators.RegexValidator('^[TF]{1}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Time_based',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_id', models.IntegerField(unique=True)),
                ('json_id', models.TextField(max_length=1000)),
            ],
        ),
    ]
